cloud_in : merged_pointcloud 
cloud_out : filtered_pointcloud 
sensor_frame : base_link 
use_rgb : false
max_queue_size : 10
min_sensor_dist: 0.01
self_see_default_padding : 0.5
self_see_default_scale : 1.0
keep_organized : false
robot_link_names : ["base_link", "link_1", "link_2", "link_3", "link_4", "link_5", "link_6", "tool0", "ati_coupler`",
                    "ee", "tool1", "gripper_dummy_link", "front_buck", "front_rack"]
