cloud_in : camera/depth/points
cloud_out : camera/depth/filtered_points
sensor_frame : camera_rgb_optical_frame
use_rgb : false
max_queue_size : 10
min_sensor_dist: 0.01
self_see_default_padding : 0.03
self_see_default_scale : 1.0
keep_organized : false
robot_link_names : ["base_link", "shoulder_link", "upper_arm_link", "forearm_link", "wrist_1_link", "wrist_2_link", "wrist_3_link", "tool0", "robotiq_manipulator_link",
                    "right_outer_finger", "left_outer_finger", "right_inner_finger", "left_inner_finger", "right_inner_knuckle", "left_inner_knuckle",
                    "right_outer_knuckle", "left_outer_knuckle", "ee_link", "robotiq_85_base_link"]
